version: ${DOCKER_COMPOSE_VERSION}
services:
  cs:
    build:
      context: ${CS_DIR}
      dockerfile: ${DOCKERFILE}
    volumes:
      - ${LOGS_DIR}:${DOCKER_LOGS_DIR}
      - ${CONFIG_FILE_PATH}:${DOCKER_CONFIG_FILE_PATH}

  js:
    build:
      context: ${JS_DIR}
      dockerfile: ${DOCKERFILE}
    volumes:
      - ${LOGS_DIR}:${DOCKER_LOGS_DIR}
      - ${CONFIG_FILE_PATH}:${DOCKER_CONFIG_FILE_PATH}

  py:
    build:
      context: ${PY_DIR}
      dockerfile: ${DOCKERFILE}
    volumes:
      - ${LOGS_DIR}:${DOCKER_LOGS_DIR}
      - ${CONFIG_FILE_PATH}:${DOCKER_CONFIG_FILE_PATH}

  java12:
    build:
      context: ${JAVA12_DIR}
      dockerfile: ${DOCKERFILE}
    volumes:
      - ${LOGS_DIR}:${DOCKER_LOGS_DIR}
      - ${CONFIG_FILE_PATH}:${DOCKER_CONFIG_FILE_PATH}

  java11:
    build:
      context: ${JAVA11_DIR}
      dockerfile: ${DOCKERFILE}
    volumes:
      - ${LOGS_DIR}:${DOCKER_LOGS_DIR}
      - ${CONFIG_FILE_PATH}:${DOCKER_CONFIG_FILE_PATH}

  java10:
    build:
      context: ${JAVA10_DIR}
      dockerfile: ${DOCKERFILE}
    volumes:
      - ${LOGS_DIR}:${DOCKER_LOGS_DIR}
      - ${CONFIG_FILE_PATH}:${DOCKER_CONFIG_FILE_PATH}
