version: "3.8"
services:
  cs:
    build:
      context: ./cs
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./sql_tests_config.json:/config.json

  js:
    build:
      context: ./js
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    volumes:
      - ./sql_tests_config.json:/config.json

  py:
    build:
      context: ./python
      dockerfile: Dockerfile
    ports:
      - "8002:80"
    volumes:
      - ./sql_tests_config.json:/config.json

  java12:
    build:
      context: ./java/jdbc_12_4_2
      dockerfile: Dockerfile
    ports:
      - "8003:80"
    volumes:
      - ./sql_tests_config.json:/config.json

  java11:
    build:
      context: ./java/jdbc_11_2_3
      dockerfile: Dockerfile
    ports:
      - "8004:80"
    volumes:
      - ./sql_tests_config.json:/config.json

  java10:
    build:
      context: ./java/jdbc_10_2_3
      dockerfile: Dockerfile
    ports:
      - "8005:80"
    volumes:
      - ./sql_tests_config.json:/config.json
