version: "3.8"
services:
  cs:
    build:
      context: ./cs
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./sql_tests_config.json:/config.json

  js:
    build:
      context: ./js
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    volumes:
      - ./sql_tests_config.json:/config.json

  py:
    build:
      context: ./python
      dockerfile: Dockerfile
    ports:
      - "8002:80"
    volumes:
      - ./sql_tests_config.json:/config.json
